import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Jamal Hospital",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png", // or "/favicon.png"
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[1280px] mx-auto w-full`}
      >
        {children}
        <Toaster
          position="top-right"
          toastOptions={{
            success: {
              style: { background: "green", color: "white" },
            },
            error: {
              style: { background: "red", color: "white" },
            },
          }}
        />
      </body>
    </html>
  );
}
